
[functions.fetch-gmail]
enabled = true
verify_jwt = true
import_map = "./functions/fetch-gmail/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fetch-gmail/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fetch-gmail/*.html" ]

[functions.manage-connected-account]
enabled = true
verify_jwt = true
import_map = "./functions/manage-connected-account/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/manage-connected-account/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/manage-connected-account/*.html" ]

[functions.groq]
enabled = true
verify_jwt = false
# import_map = "./functions/groq/deno.json"
entrypoint = "./functions/groq/index.ts"

[functions.ollama]
enabled = true
verify_jwt = false
# import_map = "./functions/ollama/deno.json"
entrypoint = "./functions/ollama/index.ts"